In [2]:
import torch
print(torch.__version__)

2.0.1+cu117


In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim


0

In [5]:
#Get tensor as py int
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,7],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 7],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 7],
        [2, 4, 5]])

### RANDOM TENSORS

Start with rand tesnors and adjust those random numbers to better represent the data

Start random -> look at data -> update -> look -> repeat 

In [17]:
#Create a random tensor size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5467, 0.1435, 0.9038, 0.2868],
        [0.7191, 0.3822, 0.5113, 0.8428],
        [0.9026, 0.6040, 0.7634, 0.6295]])

In [18]:
#Create random tensor with simlar shape to image tensor
rand_img_size_tensor = torch.rand(size=(3, 224, 224)) #height, width, color channels
rand_img_size_tensor.shape,  rand_img_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zero and Ones Tensor

In [19]:
zeros = torch.zeros(size= (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size= (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Tensor Ranges

In [21]:
#Use torch.range()

one_ten =torch.arange(start=1,end=11,step=1)
one_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
ten_zeros = torch.zeros_like(input=one_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [23]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None, #changes data type/precision one of 3 big errors
                               device="cuda", #default is cpu
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [26]:
int32t = torch.tensor([3,6,9],dtype=torch.int32 , device="cuda")
int32t

tensor([3, 6, 9], device='cuda:0', dtype=torch.int32)

In [27]:
float_32_tensor * int32t

tensor([ 9., 36., 81.], device='cuda:0')

### Getting info from tensors


In [28]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0329, 0.7352, 0.6434, 0.0267],
        [0.4087, 0.4714, 0.9583, 0.8110],
        [0.7970, 0.3880, 0.1970, 0.8847]])

In [29]:
#Find details
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}") #defaults to float
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU


tensor([[0.0329, 0.7352, 0.6434, 0.0267],
        [0.4087, 0.4714, 0.9583, 0.8110],
        [0.7970, 0.3880, 0.1970, 0.8847]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Manipulating Tensors


In [30]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [31]:
tensor * 10

tensor([10, 20, 30])

In [32]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [33]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [34]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Mult

In [35]:
#Elementwise
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [36]:
#Matrix mul
torch.matmul(tensor,tensor)

tensor(14)

In [37]:
#Matrix mul by hand
1*1 + 2*2 + 3*3

14

In [38]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 0 ns


In [39]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### Common error: shape errors
1. Inner dimmensions must match
2. Result matrix is shape of outer dim


In [40]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)
torch.mm(tensor_A,tensor_B.T) #transpose one tensor

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [41]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


### Tensor Aggregation

In [42]:
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [43]:
print(f"Minimum: {x.min()}") #torch.min(x)
print(f"Maximum: {x.max()}") #torch.max(x)
# print(f"Mean: {x.mean()}") # this will error since not float or complex
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype #torch.mean(x.type(float32))
print(f"Sum: {x.sum()}") #torch.sum(x)

Minimum: 1
Maximum: 91
Mean: 46.0
Sum: 460


In [44]:
#Positional Values
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [45]:
x[x.argmax()]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezing tensors

Reshape- Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().
View- Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
Stack- Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
Squeeze- Squeezes input to remove all the dimenions with value 1.
Unsqueeze- Returns input with a dimension value of 1 added at dim.
Permute- Returns a view of the original input with its dimensions permuted (rearranged) to dims.

In [46]:
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [47]:
#Reshape new mem

x_reshape = x.reshape(1,9)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [48]:
#View shared mem
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [49]:
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [50]:
#Stack Tensors

x_stacked = torch.stack([x,x,x,x], dim =0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [51]:
#Squeeze
print(f"Previous tensor: {x_reshape}")
print(f"Previous shape: {x_reshape.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshape.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [52]:
#Unsqueeze

print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [53]:
#Permute

x_original = torch.rand(size=(224, 224, 3))# h w cc

# Rearange dims
x_permuted = x_original.permute(2, 0, 1) # shifts dims 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #cc h w

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [54]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0] #shared

(tensor(728218.), tensor(728218.))

### Indexing

In [55]:
x = torch.arange(1, 10).reshape(1,3,3)
x,x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [60]:
#Index on tensor outermost dim

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [61]:
#Index middle dim

x[0][0]

tensor([1, 2, 3])

In [65]:
#Index innermost dim

x[0][2][2]

tensor(9)

In [66]:
#Use : to select all items in a dimension

x[:,0]

tensor([[1, 2, 3]])

In [67]:
#Get all 1st dim but only index 1st item in 2nd dim

x[:,:,1]

tensor([[2, 5, 8]])

In [68]:
#Get index 0 of 0th and 1st dimension and all values of 2nd dimension

x[0,0,:]

tensor([1, 2, 3])

In [69]:
#Index on x to return 9 and 3,6,9

x[0,2,2], x[0,:,2]

(tensor(9), tensor([3, 6, 9]))