In [3]:
import torch
print(torch.__version__)

2.0.1+cu117


In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim


0

In [6]:
#Get tensor as py int
scalar.item()

7

In [7]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,7],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 7],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 7],
        [2, 4, 5]])

### RANDOM TENSORS

Start with rand tesnors and adjust those random numbers to better represent the data

Start random -> look at data -> update -> look -> repeat 

In [20]:
#Create a random tensor size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0103, 0.7032, 0.6126, 0.4688],
        [0.9878, 0.1431, 0.6851, 0.0757],
        [0.9983, 0.6099, 0.4245, 0.8270]])

In [21]:
random_tensor.ndim

2

In [23]:
random_tensor.shape

torch.Size([3, 4])